epochs: 10
gamma: 0.99
clip: 0.1
lr: 2.5e-4
eps: 1.0e-5
gae_lambda: 0.95
entropy_coeff: 0.01
value_coefficient: 0.5
max_grad_norm: 0.5
minibatch_number: 1
target_kl: 0.02
fc: 256
message_type: 'action'
